# Generated by Django 5.1 on 2024-08-10 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_gender_customuser_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='area',
            new_name='district',
        ),
    ]
