# Generated by Django 5.1 on 2024-08-09 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='state_master',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('state_name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'States and Union Territories',
            },
        ),
        migrations.CreateModel(
            name='district_master',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('district_name', models.CharField(max_length=150, unique=True)),
                ('state_id', models.IntegerField(blank=True, null=True)),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.state_master', to_field='state_name')),
            ],
        ),
    ]
